### ISSUE TITLE
Improve Delft3dfm modelbuilder workflow

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares-research/EditoServices#1]
Initialize service:
- Login to EDITO datalab: https://datalab.dive.edito.eu/
- `Service Catalog` >> `Ocean modelling` >> `Delft3dfm-modelbuilder` >> `Launch`
- `Launch`
- this will initialize a Python environment with the JupyterLab IDE and dfm_tools installed
- the environment will also include an extended copy of the dfm_tools modelbuilder notebook

Run the modelbuilder:
- Open `modelbuilder_example_edito.ipynb`
- optionally, update spatial/temporal extent in block [2]
- optionally, adjust the min/max grid resolution with `dxy` in block [2] and `min_edge_size` in block [5].
- optionally adjust anything else in the notebook
- restart kernel and run all cells by clicking ![image](https://github.com/Deltares-research/EditoServices/assets/60435591/9e4be75f-1072-41dc-89f4-0c4f6c6ed641)
- generates a folder with Delft3D FM model input files for the requested spatial and temporal extent
- the last cell of the notebook uploads the model to your S3 bucket, resulting in a folder called DFM_INPUT

run the D-FlowFM model with another service:
- make sure you have the "DFM_INPUT" folder in your s3 bucket (including a run_docker.sh)
- `Process Catalog` >> `Ocean modelling` >> `Delft3dfm-run-docker` >> `Launch`
- `Launch`
- After approximately 3-6 minutes, this results in a `DFM_OUTPUT` folder in your s3 bucket

Remaining issues (helm chart):
- [x] replace with custom service that includes init and credentials already: https://gitlab.mercator-ocean.fr/pub/edito-infra/helm-charts/playground/-/merge_requests/26
- [x] add note about credentials to the service initialization
- [x] update notes about deletion
- [x] set minimal requirements (memory, cpu amount, cpu clocktime, diskspace, bandwith, maybe more)

Remaining issues (init.sh and extend_modelbuilder_notebook.py)
- [x] in init.sh: after copying ipynb, add cell that calls a to be created `upload_model_to_s3(dir_model)` function and supplying the correct foldername/dir_model to that function
- [x] ipynb/py files are downloaded twice. Seems like init script is executed twice, which might be a bug in edito
- [x] clear notebook output with `jupyter nbconvert --clear-output --inplace my_notebook.ipynb`
- [x] stretchtype is manually to zero in extra notebook cell until https://github.com/Deltares/HYDROLIB-core/issues/691 is fixed >> is now -1 in general notebook already and this works properly on EDITO also
- [x] move to 3D by changing flag in start of notebook instead of enabling sal/tem afterwards (model now takes 6 minutes to run but it works)
- [ ] install from pypi instead of main branch (do this when the modelbuilder is complete)

Remaining issues (modelbuilder, notebook and run_docker.sh):
- [x] flexible (or generic) model input folder name
- [x] `create_model_exec_files` is not used yet since multicore dimr cannot be parsed and sequential dimr returns nproc=0 instead of 1: https://github.com/Deltares/HYDROLIB-core/issues/562 >> https://github.com/Deltares/dfm_tools/issues/890 >> require minimal dfmt version and simplify upload script
- [x] https://gitlab.mercator-ocean.fr/pub/edito-infra/service-helm-charts/-/merge_requests/27/
- [x] add `temperature=1` and `salinity=1` (including heatfluxmodel comment), check runtime >> not required since we now use 3D run
- [x] prevent the need for copy-pasting the password when initializing the service >> no priority
- [x] maybe merge partitions (decoimpact needs this) with delft3dfm mapmerge in run_docker.sh. Can the d-ecoimpact service find both sequential/merged nc file since they have different names? >> UPDATE 29-01-2024: D-EcoImpact now accepts partitioned input, this is also released in the docker for EDITO (https://issuetracker.deltares.nl/browse/DEI-254)
- [x] parallel run fails (`"BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES    ====    RANK 0 PID 38 RUNNING AT delft3dfm-run-docker-996653-2qw9c    ====    KILLED BY SIGNAL: 1 (Segmentation Fault)"`), are we allowed to use multiple cores on EDITO? See also comment in current dockerfile about how to run it, like ulimit and shm-size, maybe we have to demand n cores here also? >> no priority right now >> this is still an issue with new docker version (2025.02) >> resolved after adding process line to dimr_config.xml
- [x] https://github.com/Deltares/dfm_tools/issues/729
- [x] more flexible changing of nparts after hydrolib-core release including fix of https://github.com/Deltares/HYDROLIB-core/issues/853
- [ ] add waq processes to model (and more): https://github.com/Deltares/dfm_tools/issues/515

Remaining issues (s3 upload):
- [x] flexible (or generic) model input folder name
- [x] convert to function so we can call it from the ipynb notebook directly
- [x] prevent the need for adding `run_docker.sh` in this script, first solve https://github.com/Deltares/HYDROLIB-core/issues/562
- [x] simplify the s3 upload commands by avoiding the need for a temp directory
- [x] s3 token is not permanently valid, even not two days, increase this to much more >> has been not much of an issue, so skip for now

Remaining issues (running delft3dfm):
- [x] no access rights for JV
- [x] currently fails since [job.yaml](https://gitlab.mercator-ocean.fr/pub/edito-infra/process-helm-charts/-/blob/main/ocean-modelling/delft3dfm-demo/templates/job.yaml?ref_type=heads) expects the folder `Vietnam_model` to exist. [upload_model.py](https://github.com/Deltares-research/EditoServices/blob/main/modelbuilder/upload_model.py) now always renames this to `DFM_model`, which might not be the best name (`delft3dfm_model` would be a better alternative).
- [x] https://gitlab.mercator-ocean.fr/pub/edito-infra/process-helm-charts/-/merge_requests/10 fixes this, and it also renames the output folder from something like `DFM_OUTPUT_Vietnam` to `DFM_OUTPUT`.
- [x] service crashes also if model run is succesful. This happens for both 2D as 3D. Furthermore, the mapfile is missing from the s3 bucket, might be the cause of the failed process. >> https://gitlab.mercator-ocean.fr/pub/edito-infra/process-helm-charts/-/merge_requests/18
- [x] crash/message if crash, instead of just running service and no output (add process text to screen like dfm-modelbuilder) >> debug logs via https://pub.pages.mercator-ocean.fr/edito-infra/edito-tutorials-content/#/Contribution/debug-while-contributing
- [x] run with new docker image from containers.deltares.nl: https://issuetracker.deltares.nl/browse/PWES-265: wait for publish of [Process Playground MR#41](https://gitlab.mercator-ocean.fr/pub/edito-infra/process-playground/-/merge_requests/41) >> [Process Helm Charts MR#21](https://gitlab.mercator-ocean.fr/pub/edito-infra/process-helm-charts/-/merge_requests/21)
- [x] uncomment `SYS_RESOURCES` in job.yaml >> first await discussion whether it is allowed >> not allowed and it works for now
- [x] update to Delft3D FM 2026.01: https://gitlab.mercator-ocean.fr/pub/edito-infra/process-helm-charts/-/merge_requests/40
- [ ] requested resources in values.yml (?) are not the defaults when starting the process in the EDITO interface (sliders have different values than in the configuration file)
- [ ] delete "DFM_OUTPUT" if already exists on S3 before uploading, so the upload is always clean (otherwise different partition settings will make a mess of the folder)
- [ ] add post-processing notebook/service?
